#!/usr/bin/env node
/**
 * Live-iteration bridge: writes a gitignored dev shim into .pi/extensions/ so
 * pi sessions opened in this repo auto-discover the pi-wake extension FROM
 * SOURCE. Combine with /reload (hot-reload for auto-discovered extensions):
 *
 *   npm run dev:link   # once (or after removing it)
 *   <open pi here>     # widget/status render from the repo source
 *   <edit *.ts>        # iterate...
 *   /reload            # re-imports the extension - no new session needed
 *
 * The shim is deliberately NOT committed: shipping it would double-load the
 * extension for everyone else (tool-name conflict) and pin their sessions to
 * this checkout. Remove with `npm run dev:unlink`.
 */
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const repoRoot = path.resolve(process.cwd());
const shimDir = path.join(repoRoot, ".pi", "extensions");
const shimPath = path.join(shimDir, "pi-wake.dev.ts");

if (process.argv.includes("--unlink")) {
	await rm(shimPath, { force: true });
	console.log(`dev:link removed (${path.relative(repoRoot, shimPath)})`);
	process.exit(0);
}

const isRepo = await readFile(path.join(repoRoot, "package.json")).then((text) => JSON.parse(text).name === "pi-wake").catch(() => false);
if (!isRepo) throw new Error("run this from the pi-wake repo root");
await mkdir(shimDir, { recursive: true });
await writeFile(shimPath, `// Generated by npm run dev:link - gitignored on purpose, do not commit.
// Re-exports the repo-source extension so /reload picks up edits live.
import piWake from "../../extensions/pi-wake/index.ts";
export default piWake;
`);
console.log(`dev shim written: ${path.relative(repoRoot, shimPath)}`);
console.log("open pi in this repo, then /reload after edits; remove with npm run dev:unlink");

